// Curated list of ~500 crypto/blockchain/ZK-related phrases for random seed generation
// Categories: Cryptography, Blockchain, Ethereum, ZK Proofs, DeFi, NFTs, Memes

export const SEED_PHRASES: string[] = [
  // Zero Knowledge & Cryptography
  "Zero Knowledge",
  "ZK Proof",
  "ZK Rollup",
  "SNARK",
  "STARK",
  "Validity Proof",
  "Merkle Tree",
  "Merkle Root",
  "Hash Function",
  "SHA256",
  "Keccak",
  "Elliptic Curve",
  "Digital Signature",
  "Public Key",
  "Private Key",
  "Cryptographic",
  "Encryption",
  "Decryption",
  "Cipher",
  "Plaintext",
  "Ciphertext",
  "Nonce",
  "Salt",
  "Entropy",
  "Random Oracle",
  "Commitment",
  "Witness",
  "Prover",
  "Verifier",
  "Trusted Setup",
  "Circuit",
  "Constraint",
  "R1CS",
  "Polynomial",
  "Groth16",
  "Plonk",
  "Nova",
  "Halo",
  "Recursion",
  "Folding",
  "Accumulator",
  "Pedersen",
  "Poseidon",
  "MiMC",
  "Bulletproof",
  "Range Proof",
  "Membership Proof",
  "Inclusion Proof",
  "Exclusion Proof",

  // Blockchain Core
  "Blockchain",
  "Block Height",
  "Block Hash",
  "Genesis Block",
  "Consensus",
  "Proof of Work",
  "Proof of Stake",
  "Validator",
  "Node",
  "Full Node",
  "Light Client",
  "Finality",
  "Fork",
  "Hard Fork",
  "Soft Fork",
  "Reorg",
  "Orphan Block",
  "Uncle Block",
  "Timestamp",
  "Difficulty",
  "Target",
  "Mining",
  "Miner",
  "Hash Rate",
  "Mempool",
  "Transaction",
  "UTXO",
  "Account Model",
  "State Root",
  "Trie",
  "Patricia Trie",
  "Receipt",
  "Log",
  "Event",
  "Topic",
  "Index",

  // Ethereum Specific
  "Ethereum",
  "Ether",
  "Wei",
  "Gwei",
  "Gas",
  "Gas Limit",
  "Gas Price",
  "Base Fee",
  "Priority Fee",
  "EIP 1559",
  "Smart Contract",
  "Solidity",
  "Vyper",
  "EVM",
  "Bytecode",
  "Opcode",
  "Storage",
  "Memory",
  "Calldata",
  "Stack",
  "ABI",
  "Interface",
  "Function",
  "Selector",
  "Modifier",
  "Fallback",
  "Receive",
  "Constructor",
  "Proxy",
  "Implementation",
  "Delegate Call",
  "Static Call",
  "Create2",
  "Self Destruct",
  "Revert",
  "Require",
  "Assert",

  // Layer 2 & Scaling
  "Layer 2",
  "Layer Two",
  "L2",
  "Rollup",
  "Optimistic",
  "ZK Rollup",
  "Validium",
  "Volition",
  "Data Availability",
  "Sequencer",
  "Batch",
  "Compression",
  "Blob",
  "Proto Danksharding",
  "Danksharding",
  "Shard",
  "Beacon Chain",
  "The Merge",
  "Shanghai",
  "Cancun",
  "Dencun",
  "Plasma",
  "State Channel",
  "Payment Channel",
  "Lightning",
  "Arbitrum",
  "Optimism",
  "zkSync",
  "StarkNet",
  "Polygon zkEVM",
  "Scroll",
  "Linea",
  "Base",
  "Mantle",
  "Blast",
  "Mode",
  "Zora",

  // DeFi
  "DeFi",
  "Decentralized",
  "DEX",
  "AMM",
  "Liquidity Pool",
  "LP Token",
  "Swap",
  "Slippage",
  "Price Impact",
  "Impermanent Loss",
  "Yield",
  "APY",
  "APR",
  "Farming",
  "Staking",
  "Unstaking",
  "Bonding",
  "Vesting",
  "Lockup",
  "Timelock",
  "Governance",
  "Proposal",
  "Vote",
  "Quorum",
  "Snapshot",
  "Delegation",
  "Lending",
  "Borrowing",
  "Collateral",
  "Liquidation",
  "Health Factor",
  "Loan to Value",
  "Oracle",
  "Price Feed",
  "TWAP",
  "Flash Loan",
  "Arbitrage",
  "MEV",
  "Frontrun",
  "Backrun",
  "Sandwich",
  "Searcher",
  "Builder",
  "Proposer",
  "PBS",

  // Tokens & Standards
  "Token",
  "ERC20",
  "ERC721",
  "ERC1155",
  "ERC4626",
  "Fungible",
  "Non Fungible",
  "NFT",
  "Mint",
  "Burn",
  "Transfer",
  "Approve",
  "Allowance",
  "Permit",
  "Permit2",
  "Multicall",
  "Batch Transfer",
  "Safe Transfer",
  "Metadata",
  "Token URI",
  "Base URI",
  "Royalty",
  "Soul Bound",
  "SBT",
  "Airdrop",
  "Claim",
  "Merkle Drop",
  "Whitelist",
  "Allowlist",

  // Wallets & Identity
  "Wallet",
  "Hot Wallet",
  "Cold Wallet",
  "Hardware Wallet",
  "Seed Phrase",
  "Mnemonic",
  "BIP39",
  "Derivation Path",
  "HD Wallet",
  "Keystore",
  "Passphrase",
  "Recovery",
  "Backup",
  "Multisig",
  "Safe",
  "Gnosis Safe",
  "Account Abstraction",
  "Smart Account",
  "Bundler",
  "Paymaster",
  "Session Key",
  "Social Recovery",
  "Guardian",
  "ENS",
  "Domain",
  "Resolver",
  "Avatar",
  "Text Record",
  "Address Record",

  // Security
  "Security",
  "Audit",
  "Bug Bounty",
  "Exploit",
  "Vulnerability",
  "Reentrancy",
  "Overflow",
  "Underflow",
  "Access Control",
  "Ownable",
  "Role",
  "Admin",
  "Pause",
  "Emergency",
  "Circuit Breaker",
  "Rate Limit",
  "Denial of Service",
  "Phishing",
  "Rug Pull",
  "Honeypot",
  "Scam",
  "DYOR",
  "NFA",
  "Verify",
  "Etherscan",

  // Development
  "Developer",
  "Smart Contract",
  "Deploy",
  "Verify",
  "Testnet",
  "Mainnet",
  "Goerli",
  "Sepolia",
  "Holesky",
  "Hardhat",
  "Foundry",
  "Forge",
  "Cast",
  "Anvil",
  "Truffle",
  "Remix",
  "Tenderly",
  "Alchemy",
  "Infura",
  "QuickNode",
  "RPC",
  "JSON RPC",
  "Web3",
  "Ethers",
  "Viem",
  "Wagmi",
  "Rainbow Kit",
  "Connect Kit",
  "Web3Modal",
  "Wallet Connect",

  // Protocols & Projects
  "Uniswap",
  "Aave",
  "Compound",
  "MakerDAO",
  "DAI",
  "Lido",
  "Rocket Pool",
  "Curve",
  "Convex",
  "Yearn",
  "Balancer",
  "Sushi",
  "Pancake",
  "1inch",
  "Cowswap",
  "Paraswap",
  "OpenSea",
  "Blur",
  "LooksRare",
  "Zora",
  "Manifold",
  "Sound",
  "Mirror",
  "Lens",
  "Farcaster",
  "ENS",
  "Chainlink",
  "The Graph",
  "IPFS",
  "Arweave",
  "Filecoin",

  // People & History
  "Satoshi",
  "Vitalik",
  "Buterin",
  "Nakamoto",
  "Hal Finney",
  "Nick Szabo",
  "Gavin Wood",
  "Joseph Lubin",
  "Charles Hoskinson",
  "Cypherpunk",
  "Crypto Anarchist",
  "Whitepaper",
  "Yellow Paper",
  "DAO Hack",
  "The DAO",
  "Ice Age",
  "Difficulty Bomb",
  "London Fork",
  "Constantinople",
  "Berlin",
  "Istanbul",

  // Memes & Culture
  "WAGMI",
  "NGMI",
  "GM",
  "GN",
  "Gm Frens",
  "Wen Moon",
  "Wen Lambo",
  "Diamond Hands",
  "Paper Hands",
  "HODL",
  "Hodler",
  "Bagholder",
  "Rekt",
  "Rugged",
  "Mooning",
  "Pumping",
  "Dumping",
  "Fomo",
  "Fud",
  "Shill",
  "Ape",
  "Aping In",
  "Degen",
  "Anon",
  "Fren",
  "Ser",
  "Probably Nothing",
  "Few Understand",
  "Up Only",
  "Number Go Up",
  "Stack Sats",
  "Buy The Dip",
  "Sell The News",
  "Generational Wealth",
  "Life Changing",
  "To The Moon",
  "Flippening",
  "Supercycle",
  "Bull Run",
  "Bear Market",
  "Crab Market",
  "Goblin Town",
  "Valhalla",
  "LFG",
  "IYKYK",
  "NGL",
  "Based",
  "Chad",
  "Gigabrain",
  "Smoothbrain",
  "Cope",
  "Hopium",
  "Copium",
  "Alpha",
  "Beta",
  "OG",
  "Normie",
  "Pleb",
  "Whale",
  "Shrimp",
  "Fish",
  "Dolphin",
  "Exit Liquidity",
  "Liquidity",
  "Dry Powder",
  "Sidelines",

  // Trading & Markets
  "Trading",
  "Trader",
  "Long",
  "Short",
  "Leverage",
  "Margin",
  "Liquidated",
  "Stop Loss",
  "Take Profit",
  "Limit Order",
  "Market Order",
  "Order Book",
  "Bid",
  "Ask",
  "Spread",
  "Volume",
  "Market Cap",
  "Fully Diluted",
  "Circulating",
  "Total Supply",
  "Max Supply",
  "Inflation",
  "Deflation",
  "Burn Rate",
  "Emission",
  "Halving",
  "All Time High",
  "ATH",
  "ATL",
  "Support",
  "Resistance",
  "Breakout",
  "Breakdown",
  "Reversal",
  "Trend",
  "Bullish",
  "Bearish",
  "Sideways",

  // Privacy
  "Privacy",
  "Anonymous",
  "Pseudonymous",
  "Mixer",
  "Tumbler",
  "Tornado",
  "Zcash",
  "Monero",
  "Ring Signature",
  "Stealth Address",
  "Confidential",
  "Shielded",
  "Transparent",
  "Private Input",
  "Public Output",
  "Selective Disclosure",
  "Credential",
  "Attestation",
  "Proof of Humanity",
  "Worldcoin",
  "Sismo",
  "Semaphore",

  // Governance & DAOs
  "DAO",
  "Treasury",
  "Multisig",
  "Council",
  "Committee",
  "Working Group",
  "Contributor",
  "Core Team",
  "Community",
  "Token Holder",
  "Stake Weighted",
  "Quadratic Voting",
  "Conviction Voting",
  "Rage Quit",
  "Moloch",
  "Nouns",
  "Aragon",
  "Tally",
  "Boardroom",

  // Infrastructure
  "Infrastructure",
  "Protocol",
  "Network",
  "Mainnet",
  "Testnet",
  "Devnet",
  "Bridge",
  "Cross Chain",
  "Interoperability",
  "Cosmos",
  "IBC",
  "Polkadot",
  "Substrate",
  "Avalanche",
  "Solana",
  "Near",
  "Sui",
  "Aptos",
  "Move",
  "Rust",
  "Cairo",

  // Misc Technical
  "Bytecode",
  "Assembly",
  "Yul",
  "Huff",
  "Optimization",
  "Gas Golf",
  "Inline Assembly",
  "Bit Manipulation",
  "Packed Storage",
  "Struct Packing",
  "Memory Layout",
  "Stack Too Deep",
  "Contract Size",
  "Spurious Dragon",
  "EIP",
  "ERC",
  "Standard",
  "Draft",
  "Final",
  "Last Call",

  // Fun Phrases
  "Maze King",
  "Key Master",
  "Crown Seeker",
  "Path Finder",
  "Wall Walker",
  "Grid Runner",
  "Crypto Quest",
  "Block Explorer",
  "Chain Walker",
  "Hash Hunter",
  "Proof Seeker",
  "Zero Hero",
  "Merkle Maze",
  "Binary Labyrinth",
  "Digital Dungeon",
  "Pixel Pioneer",
  "Code Breaker",
  "Cipher Solver",
  "Secret Keeper",
  "Truth Teller",
];

// Get a random phrase from the list
export function getRandomPhrase(): string {
  const index = Math.floor(Math.random() * SEED_PHRASES.length);
  return SEED_PHRASES[index];
}

// Get multiple unique random phrases
export function getRandomPhrases(count: number): string[] {
  const shuffled = [...SEED_PHRASES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, SEED_PHRASES.length));
}
