#!/usr/bin/env node
/**
 * Generate palette codegen artifacts from palette/paletteRecipe.json.
 *
 * Emits:
 *   - frontend/src/lib/paletteRecipe.generated.ts
 *   - contracts/src/MazePalette.sol
 *
 * Both files share the same recipe so the live canvas and the on-chain SVG
 * never drift on the canonical structural fields. Idempotent: a clean
 * second run produces no diff.
 *
 * Usage: node scripts/generate-palette.js  (or `just generate-palette`)
 */

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.join(__dirname, '..');
const RECIPE_FILE = path.join(PROJECT_ROOT, 'palette/paletteRecipe.json');
const TS_OUTPUT = path.join(PROJECT_ROOT, 'frontend/src/lib/paletteRecipe.generated.ts');
const SOL_OUTPUT = path.join(PROJECT_ROOT, 'contracts/src/MazePalette.sol');

const C = {
  RED: '\x1b[0;31m',
  GREEN: '\x1b[0;32m',
  YELLOW: '\x1b[1;33m',
  BLUE: '\x1b[0;34m',
  NC: '\x1b[0m',
};
const log = (color, tag, msg) => console.log(`${color}[${tag}]${C.NC} ${msg}`);
const die = (msg) => {
  log(C.RED, 'palette', `Error: ${msg}`);
  process.exit(1);
};

function loadRecipe() {
  if (!fs.existsSync(RECIPE_FILE)) die(`Recipe file not found: ${RECIPE_FILE}`);
  const raw = fs.readFileSync(RECIPE_FILE, 'utf8');
  const recipe = JSON.parse(raw);
  if (!Array.isArray(recipe.fields) || recipe.fields.length === 0) {
    die('Recipe must have a non-empty `fields` array');
  }
  for (const f of recipe.fields) {
    if (!f.name || typeof f.name !== 'string') die(`Field missing name: ${JSON.stringify(f)}`);
    if (!f.hue || (f.hue.type !== 'offset' && f.hue.type !== 'constant')) {
      die(`Field ${f.name}: hue.type must be 'offset' or 'constant'`);
    }
    if (f.hue.type === 'offset' && !Number.isInteger(f.hue.offset)) {
      die(`Field ${f.name}: hue.offset must be an integer (got ${f.hue.offset})`);
    }
    if (f.hue.type === 'constant' && !Number.isInteger(f.hue.value)) {
      die(`Field ${f.name}: hue.value must be an integer (got ${f.hue.value})`);
    }
    if (!Number.isInteger(f.s) || f.s < 0 || f.s > 100) die(`Field ${f.name}: s must be 0..100`);
    if (!Number.isInteger(f.l) || f.l < 0 || f.l > 100) die(`Field ${f.name}: l must be 0..100`);
    if (typeof f.onChain !== 'boolean') die(`Field ${f.name}: onChain must be boolean`);
  }
  return recipe;
}

function generateTypeScript(recipe) {
  const fieldType = recipe.fields.map((f) => `'${f.name}'`).join(' | ');
  const entries = recipe.fields
    .map((f) => {
      const hue =
        f.hue.type === 'constant'
          ? `{ type: 'constant', value: ${f.hue.value} }`
          : `{ type: 'offset', offset: ${f.hue.offset} }`;
      return `  { name: '${f.name}', hue: ${hue}, s: ${f.s}, l: ${f.l}, onChain: ${f.onChain} },`;
    })
    .join('\n');

  return `/**
 * Auto-generated palette recipe.
 * Source: palette/paletteRecipe.json
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Regenerate with: just generate-palette
 *
 * The on-chain SVG renderer (contracts/src/MazePalette.sol) is generated from
 * the same source. Hand-edits to either file will silently drift the live
 * canvas off the on-chain NFT — see ma-fy3 / 2026-05-05 retrospective §11.A.
 */

export type PaletteHue =
  | { type: 'constant'; value: number }
  | { type: 'offset'; offset: number };

export type PaletteFieldName = ${fieldType};

export interface PaletteField {
  name: PaletteFieldName;
  hue: PaletteHue;
  s: number;
  l: number;
  onChain: boolean;
}

export const PALETTE_RECIPE: readonly PaletteField[] = [
${entries}
] as const;

/**
 * Resolve a recipe field's hue against a given baseHue.
 * Mirrors the Solidity computation in MazePalette.sol exactly.
 */
export function resolveHue(field: PaletteField, baseHue: number): number {
  if (field.hue.type === 'constant') return field.hue.value;
  return (baseHue + field.hue.offset) % 360;
}
`;
}

function generateSolidity(recipe) {
  const onChainFields = recipe.fields.filter((f) => f.onChain);

  const structFields = onChainFields
    .map((f) => `        string ${f.name};`)
    .join('\n');

  const assignments = onChainFields
    .map((f) => {
      const doc = f.doc ? `        // ${f.doc}\n` : '';
      let hueExpr;
      if (f.hue.type === 'constant') {
        hueExpr = String(f.hue.value);
      } else if (f.hue.offset === 0) {
        hueExpr = 'baseHue';
      } else {
        hueExpr = `(baseHue + ${f.hue.offset}) % 360`;
      }
      return `${doc}        p.${f.name} = _hsl(${hueExpr}, ${f.s}, ${f.l});`;
    })
    .join('\n\n');

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Strings } from "@openzeppelin/contracts/utils/Strings.sol";

/**
 * @title MazePalette
 * @notice Auto-generated canonical palette for MazeKing.
 * @dev Source: palette/paletteRecipe.json
 *      DO NOT EDIT THIS FILE MANUALLY.
 *      Regenerate with: just generate-palette
 *
 *      The TS counterpart (frontend/src/lib/paletteRecipe.generated.ts) is
 *      generated from the same source. Hand-edits to either file silently
 *      drift the live canvas off the on-chain NFT — see ma-fy3 /
 *      2026-05-05 retrospective §11.A.
 */
library MazePalette {
    using Strings for uint256;

    struct Palette {
${structFields}
    }

    /// @dev Build an HSL palette deterministically from \`seed\`. We emit HSL
    ///      strings rather than RGB so the SVG client does the conversion —
    ///      that's free for us and keeps the bytecode small.
    function palette(uint256 seed) internal pure returns (Palette memory p) {
        uint256 baseHue = seed % 360;

${assignments}
    }

    function _hsl(uint256 h, uint256 s, uint256 l) internal pure returns (string memory) {
        return string(
            abi.encodePacked("hsl(", h.toString(), ",", s.toString(), "%,", l.toString(), "%)")
        );
    }
}
`;
}

function writeIfChanged(target, content, label) {
  const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
  if (existing === content) {
    log(C.GREEN, label, `${target} (unchanged)`);
    return false;
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, 'utf8');
  log(C.GREEN, label, `Wrote ${target}`);
  return true;
}

function main() {
  log(C.BLUE, 'palette', 'Generating palette codegen from palette/paletteRecipe.json...');
  const recipe = loadRecipe();

  log(C.YELLOW, 'palette', `Loaded ${recipe.fields.length} fields:`);
  for (const f of recipe.fields) {
    const hueStr =
      f.hue.type === 'constant' ? `h=${f.hue.value}` : `h=base+${f.hue.offset}`;
    const tag = f.onChain ? 'on-chain' : 'frontend ';
    console.log(`  [${tag}] ${f.name.padEnd(10)} ${hueStr.padEnd(12)} s=${f.s} l=${f.l}`);
  }
  console.log('');

  writeIfChanged(TS_OUTPUT, generateTypeScript(recipe), 'typescript');
  writeIfChanged(SOL_OUTPUT, generateSolidity(recipe), 'solidity');

  log(C.GREEN, 'palette', 'Generation complete!');
}

try {
  main();
} catch (err) {
  die(err.message);
}
