#!/usr/bin/env node
/**
 * Generate palette code for Sol + TS from palette/paletteRecipe.json.
 *
 * Reads palette/paletteRecipe.json (single source of truth) and emits:
 * - Solidity:    contracts/src/MazePalette.sol           (5 structural fields)
 * - TypeScript:  frontend/src/lib/paletteRecipe.generated.ts (all 8 fields)
 *
 * The Sol side only includes structural fields (wall, mazeBg, textBg, zkBg,
 * crownBg) because the on-chain SVG no longer renders entity overlays
 * (ma-e7r). The TS side includes all 8 because the live canvas still draws
 * player/key/goal glyphs.
 *
 * Idempotent — running twice produces no diff. CI uses `just verify-palette`
 * (regen + git diff --exit-code) to catch hand-edits to either generated
 * file and missed regen after recipe edits.
 *
 * Usage: node scripts/generate-palette.js
 */

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.join(__dirname, '..');
const RECIPE_FILE = path.join(PROJECT_ROOT, 'palette/paletteRecipe.json');
const SOL_OUTPUT = path.join(PROJECT_ROOT, 'contracts/src/MazePalette.sol');
const TS_OUTPUT = path.join(
  PROJECT_ROOT,
  'frontend/src/lib/paletteRecipe.generated.ts'
);

const C = {
  RED: '\x1b[0;31m',
  GREEN: '\x1b[0;32m',
  YELLOW: '\x1b[1;33m',
  BLUE: '\x1b[0;34m',
  NC: '\x1b[0m',
};

function log(color, tag, msg) {
  console.log(`${color}[${tag}]${C.NC} ${msg}`);
}

function fail(msg) {
  log(C.RED, 'palette', `Error: ${msg}`);
  process.exit(1);
}

function loadRecipe() {
  if (!fs.existsSync(RECIPE_FILE)) {
    fail(`Recipe not found: ${RECIPE_FILE}`);
  }
  const raw = fs.readFileSync(RECIPE_FILE, 'utf8');
  const recipe = JSON.parse(raw);
  validateRecipe(recipe);
  return recipe;
}

function validateRecipe(recipe) {
  if (!Array.isArray(recipe.fields) || recipe.fields.length === 0) {
    fail('recipe.fields must be a non-empty array');
  }
  if (recipe.baseHueModulus !== 360) {
    fail('baseHueModulus must be 360 (HSL hue range)');
  }
  const seen = new Set();
  for (const f of recipe.fields) {
    if (!f.name || typeof f.name !== 'string') fail('field.name required');
    if (seen.has(f.name)) fail(`duplicate field: ${f.name}`);
    seen.add(f.name);
    if (typeof f.structural !== 'boolean') fail(`${f.name}.structural must be boolean`);
    if (!f.hue || typeof f.hue !== 'object') fail(`${f.name}.hue required`);
    if (f.hue.kind !== 'offset' && f.hue.kind !== 'constant') {
      fail(`${f.name}.hue.kind must be "offset" or "constant"`);
    }
    if (!Number.isInteger(f.hue.value) || f.hue.value < 0 || f.hue.value >= 360) {
      fail(`${f.name}.hue.value must be integer in [0, 360)`);
    }
    if (!Number.isInteger(f.s) || f.s < 0 || f.s > 100) {
      fail(`${f.name}.s must be integer in [0, 100]`);
    }
    if (!Number.isInteger(f.l) || f.l < 0 || f.l > 100) {
      fail(`${f.name}.l must be integer in [0, 100]`);
    }
  }
}

const HEADER_BLURB = `AUTOGENERATED — DO NOT EDIT.
Source: palette/paletteRecipe.json
Regenerate with: just generate-palette
CI gate: just verify-palette (regenerates and asserts no diff).

The Sol and TS sides of this codegen MUST stay byte-aligned for the five
structural fields (wall, mazeBg, textBg, zkBg, crownBg). The on-chain SVG
and the live canvas read from the same recipe to prevent silent palette
drift between mint and play. See ma-fy3 for context.`;

function hueExprSol(hue) {
  if (hue.kind === 'constant') return String(hue.value);
  if (hue.value === 0) return 'baseHue';
  return `(baseHue + ${hue.value}) % 360`;
}

function generateSolidity(recipe) {
  const structural = recipe.fields.filter((f) => f.structural);

  const structFields = structural
    .map((f) => `        string ${f.name};`)
    .join('\n');

  const assignments = structural
    .map((f) => `        p.${f.name} = _hsl(${hueExprSol(f.hue)}, ${f.s}, ${f.l});`)
    .join('\n');

  const headerLines = HEADER_BLURB.split('\n')
    .map((l) => (l ? `// ${l}` : '//'))
    .join('\n');

  return `// SPDX-License-Identifier: MIT
${headerLines}
pragma solidity ^0.8.24;

import { Strings } from "@openzeppelin/contracts/utils/Strings.sol";

/// @title MazePalette
/// @notice On-chain palette for MazeRenderer. Five structural fields
///         (wall/mazeBg/textBg/zkBg/crownBg) byte-aligned with the live
///         canvas via palette/paletteRecipe.json. Entity fields
///         (player/key/goal) live in the TS side only — the on-chain SVG
///         no longer renders entity overlays (ma-e7r).
library MazePalette {
    using Strings for uint256;

    struct Palette {
${structFields}
    }

    /// @dev Build an HSL palette deterministically from \`seed\`. Emits HSL
    ///      strings rather than RGB so the SVG client does the conversion —
    ///      free for us, keeps bytecode small.
    function palette(uint256 seed) internal pure returns (Palette memory p) {
        uint256 baseHue = seed % 360;
${assignments}
    }

    function _hsl(uint256 h, uint256 s, uint256 l) internal pure returns (string memory) {
        return string(
            abi.encodePacked("hsl(", h.toString(), ",", s.toString(), "%,", l.toString(), "%)")
        );
    }
}
`;
}

function hueExprTs(hue) {
  if (hue.kind === 'constant') return String(hue.value);
  if (hue.value === 0) return 'baseHue';
  return `(baseHue + ${hue.value}) % 360`;
}

function generateTypeScript(recipe) {
  const headerLines = HEADER_BLURB.split('\n')
    .map((l) => (l ? ` * ${l}` : ' *'))
    .join('\n');

  const recipeEntries = recipe.fields
    .map((f) => {
      const hueStr =
        f.hue.kind === 'constant'
          ? `{ kind: 'constant', value: ${f.hue.value} }`
          : `{ kind: 'offset',   value: ${f.hue.value} }`;
      return `  { name: '${f.name}', structural: ${f.structural}, hue: ${hueStr}, s: ${f.s}, l: ${f.l} },`;
    })
    .join('\n');

  const paletteFields = recipe.fields
    .map((f) => `  readonly ${f.name}: HSL;`)
    .join('\n');

  const paletteAssignments = recipe.fields
    .map((f) => {
      const hueExpr = hueExprTs(f.hue);
      return `    ${f.name}: { h: ${hueExpr}, s: ${f.s}, l: ${f.l} },`;
    })
    .join('\n');

  return `/**
${headerLines}
 */

export interface HSL {
  readonly h: number;
  readonly s: number;
  readonly l: number;
}

export type HueRecipe =
  | { readonly kind: 'constant'; readonly value: number }
  | { readonly kind: 'offset'; readonly value: number };

export interface PaletteRecipeField {
  readonly name: string;
  /** True iff this field is rendered by the on-chain SVG (must match Sol). */
  readonly structural: boolean;
  readonly hue: HueRecipe;
  readonly s: number;
  readonly l: number;
}

export const PALETTE_RECIPE: readonly PaletteRecipeField[] = [
${recipeEntries}
] as const;

export const STRUCTURAL_FIELD_NAMES = PALETTE_RECIPE.filter(
  (f) => f.structural
).map((f) => f.name);

export interface CanonicalPalette {
  readonly baseHue: number;
${paletteFields}
}

/**
 * Canonical palette derived from the maze hash. The structural fields
 * (per PALETTE_RECIPE) MUST match \`MazePalette.palette()\` in
 * contracts/src/MazePalette.sol byte-for-byte — those are the colors the
 * on-chain SVG renders, and the live canvas has to agree on them. The
 * entity fields (player/key/goal) are frontend-only: the on-chain SVG no
 * longer draws character/pickup/goal overlays (ma-e7r).
 */
export function canonicalPaletteFromHash(mazeHash: string): CanonicalPalette {
  const baseHue = Number(BigInt(mazeHash) % 360n);
  return {
    baseHue,
${paletteAssignments}
  };
}

/** Format an HSL triple as the same string the on-chain renderer emits. */
export function hslString(c: HSL): string {
  return \`hsl(\${c.h},\${c.s}%,\${c.l}%)\`;
}
`;
}

function writeIfChanged(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  let prev = null;
  try {
    prev = fs.readFileSync(file, 'utf8');
  } catch (_) {
    /* missing — first generate */
  }
  if (prev === content) {
    log(C.YELLOW, 'palette', `unchanged: ${path.relative(PROJECT_ROOT, file)}`);
    return;
  }
  fs.writeFileSync(file, content, 'utf8');
  log(C.GREEN, 'palette', `wrote: ${path.relative(PROJECT_ROOT, file)}`);
}

function main() {
  log(C.BLUE, 'palette', 'Generating palette artifacts from palette/paletteRecipe.json...');
  const recipe = loadRecipe();

  log(C.YELLOW, 'palette', `${recipe.fields.length} fields (${recipe.fields.filter((f) => f.structural).length} structural)`);
  for (const f of recipe.fields) {
    const hue =
      f.hue.kind === 'constant'
        ? `h=${f.hue.value}`
        : `h=baseHue+${f.hue.value}`;
    console.log(`  ${f.structural ? '★' : ' '} ${f.name.padEnd(8)} ${hue} s=${f.s} l=${f.l}`);
  }
  console.log('');

  writeIfChanged(SOL_OUTPUT, generateSolidity(recipe));
  writeIfChanged(TS_OUTPUT, generateTypeScript(recipe));

  log(C.GREEN, 'palette', 'Generation complete.');
}

try {
  main();
} catch (err) {
  fail(err.message);
}
