/**
 * Auto-generated maze constants
 * Generated at: 2026-01-30T18:30:21.801Z
 * Source: maze-config.json
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Regenerate with: just generate-constants
 */

/** Maximum total cells in a maze (width * height) */
export const MAX_MAZE_CELLS = 3000;

/** Maximum packed bytes for cell data (2 cells per byte) */
export const MAX_PACKED_BYTES = 1500;

/** Maximum number of moves in a solution */
export const MAX_MOVES = 1000;

/**
 * Number of public inputs for ZK proof verification.
 * = 8 scalar params + MAX_PACKED_BYTES + 1 move_count
 */
export const PUBLIC_INPUTS_LENGTH = 1509;

/**
 * Number of elements used for maze identity hash (tokenId calculation).
 * = PUBLIC_INPUTS_LENGTH - 1 (excludes move_count)
 */
export const MAZE_DATA_LENGTH = 1508;
