/**
 * Auto-generated palette recipe.
 * Source: palette/paletteRecipe.json
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Regenerate with: just generate-palette
 *
 * The on-chain SVG renderer (contracts/src/MazePalette.sol) is generated from
 * the same source. Hand-edits to either file will silently drift the live
 * canvas off the on-chain NFT — see ma-fy3 / 2026-05-05 retrospective §11.A.
 */

export type PaletteHue =
  | { type: 'constant'; value: number }
  | { type: 'offset'; offset: number };

export type PaletteFieldName = 'wall' | 'mazeBg' | 'textBg' | 'zkBg' | 'crownBg' | 'player' | 'key' | 'goal';

export interface PaletteField {
  name: PaletteFieldName;
  hue: PaletteHue;
  s: number;
  l: number;
  onChain: boolean;
}

export const PALETTE_RECIPE: readonly PaletteField[] = [
  { name: 'wall', hue: { type: 'offset', offset: 0 }, s: 25, l: 22, onChain: true },
  { name: 'mazeBg', hue: { type: 'offset', offset: 30 }, s: 22, l: 80, onChain: true },
  { name: 'textBg', hue: { type: 'offset', offset: 200 }, s: 80, l: 60, onChain: true },
  { name: 'zkBg', hue: { type: 'offset', offset: 320 }, s: 80, l: 55, onChain: true },
  { name: 'crownBg', hue: { type: 'constant', value: 48 }, s: 85, l: 55, onChain: true },
  { name: 'player', hue: { type: 'constant', value: 45 }, s: 90, l: 60, onChain: false },
  { name: 'key', hue: { type: 'constant', value: 55 }, s: 85, l: 55, onChain: false },
  { name: 'goal', hue: { type: 'offset', offset: 90 }, s: 65, l: 50, onChain: false },
] as const;

/**
 * Resolve a recipe field's hue against a given baseHue.
 * Mirrors the Solidity computation in MazePalette.sol exactly.
 */
export function resolveHue(field: PaletteField, baseHue: number): number {
  if (field.hue.type === 'constant') return field.hue.value;
  return (baseHue + field.hue.offset) % 360;
}
