/**
 * AUTOGENERATED — DO NOT EDIT.
 * Source: palette/paletteRecipe.json
 * Regenerate with: just generate-palette
 * CI gate: just verify-palette (regenerates and asserts no diff).
 *
 * The Sol and TS sides of this codegen MUST stay byte-aligned for the five
 * structural fields (wall, mazeBg, textBg, zkBg, crownBg). The on-chain SVG
 * and the live canvas read from the same recipe to prevent silent palette
 * drift between mint and play. See ma-fy3 for context.
 */

export interface HSL {
  readonly h: number;
  readonly s: number;
  readonly l: number;
}

export type HueRecipe =
  | { readonly kind: 'constant'; readonly value: number }
  | { readonly kind: 'offset'; readonly value: number };

export interface PaletteRecipeField {
  readonly name: string;
  /** True iff this field is rendered by the on-chain SVG (must match Sol). */
  readonly structural: boolean;
  readonly hue: HueRecipe;
  readonly s: number;
  readonly l: number;
}

export const PALETTE_RECIPE: readonly PaletteRecipeField[] = [
  { name: 'wall', structural: true, hue: { kind: 'offset',   value: 0 }, s: 25, l: 22 },
  { name: 'mazeBg', structural: true, hue: { kind: 'offset',   value: 30 }, s: 22, l: 80 },
  { name: 'textBg', structural: true, hue: { kind: 'offset',   value: 200 }, s: 80, l: 60 },
  { name: 'zkBg', structural: true, hue: { kind: 'offset',   value: 320 }, s: 80, l: 55 },
  { name: 'crownBg', structural: true, hue: { kind: 'constant', value: 48 }, s: 85, l: 55 },
  { name: 'player', structural: false, hue: { kind: 'constant', value: 45 }, s: 90, l: 60 },
  { name: 'key', structural: false, hue: { kind: 'constant', value: 55 }, s: 85, l: 55 },
  { name: 'goal', structural: false, hue: { kind: 'offset',   value: 90 }, s: 65, l: 50 },
] as const;

export const STRUCTURAL_FIELD_NAMES = PALETTE_RECIPE.filter(
  (f) => f.structural
).map((f) => f.name);

export interface CanonicalPalette {
  readonly baseHue: number;
  readonly wall: HSL;
  readonly mazeBg: HSL;
  readonly textBg: HSL;
  readonly zkBg: HSL;
  readonly crownBg: HSL;
  readonly player: HSL;
  readonly key: HSL;
  readonly goal: HSL;
}

/**
 * Canonical palette derived from the maze hash. The structural fields
 * (per PALETTE_RECIPE) MUST match `MazePalette.palette()` in
 * contracts/src/MazePalette.sol byte-for-byte — those are the colors the
 * on-chain SVG renders, and the live canvas has to agree on them. The
 * entity fields (player/key/goal) are frontend-only: the on-chain SVG no
 * longer draws character/pickup/goal overlays (ma-e7r).
 */
export function canonicalPaletteFromHash(mazeHash: string): CanonicalPalette {
  const baseHue = Number(BigInt(mazeHash) % 360n);
  return {
    baseHue,
    wall: { h: baseHue, s: 25, l: 22 },
    mazeBg: { h: (baseHue + 30) % 360, s: 22, l: 80 },
    textBg: { h: (baseHue + 200) % 360, s: 80, l: 60 },
    zkBg: { h: (baseHue + 320) % 360, s: 80, l: 55 },
    crownBg: { h: 48, s: 85, l: 55 },
    player: { h: 45, s: 90, l: 60 },
    key: { h: 55, s: 85, l: 55 },
    goal: { h: (baseHue + 90) % 360, s: 65, l: 50 },
  };
}

/** Format an HSL triple as the same string the on-chain renderer emits. */
export function hslString(c: HSL): string {
  return `hsl(${c.h},${c.s}%,${c.l}%)`;
}
