// SPDX-License-Identifier: MIT
// AUTOGENERATED — DO NOT EDIT.
// Source: palette/paletteRecipe.json
// Regenerate with: just generate-palette
// CI gate: just verify-palette (regenerates and asserts no diff).
//
// The Sol and TS sides of this codegen MUST stay byte-aligned for the five
// structural fields (wall, mazeBg, textBg, zkBg, crownBg). The on-chain SVG
// and the live canvas read from the same recipe to prevent silent palette
// drift between mint and play. See ma-fy3 for context.
pragma solidity ^0.8.24;

import { Strings } from "@openzeppelin/contracts/utils/Strings.sol";

/// @title MazePalette
/// @notice On-chain palette for MazeRenderer. Five structural fields
///         (wall/mazeBg/textBg/zkBg/crownBg) byte-aligned with the live
///         canvas via palette/paletteRecipe.json. Entity fields
///         (player/key/goal) live in the TS side only — the on-chain SVG
///         no longer renders entity overlays (ma-e7r).
library MazePalette {
    using Strings for uint256;

    struct Palette {
        string wall;
        string mazeBg;
        string textBg;
        string zkBg;
        string crownBg;
    }

    /// @dev Build an HSL palette deterministically from `seed`. Emits HSL
    ///      strings rather than RGB so the SVG client does the conversion —
    ///      free for us, keeps bytecode small.
    function palette(uint256 seed) internal pure returns (Palette memory p) {
        uint256 baseHue = seed % 360;
        p.wall = _hsl(baseHue, 25, 22);
        p.mazeBg = _hsl((baseHue + 30) % 360, 22, 80);
        p.textBg = _hsl((baseHue + 200) % 360, 80, 60);
        p.zkBg = _hsl((baseHue + 320) % 360, 80, 55);
        p.crownBg = _hsl(48, 85, 55);
    }

    function _hsl(uint256 h, uint256 s, uint256 l) internal pure returns (string memory) {
        return string(
            abi.encodePacked("hsl(", h.toString(), ",", s.toString(), "%,", l.toString(), "%)")
        );
    }
}
