// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title MazeConstants
 * @notice Auto-generated maze constants from maze-config.json
 * @dev Generated at: 2026-05-04T13:47:27.221Z
 *      DO NOT EDIT THIS FILE MANUALLY
 *      Regenerate with: just generate-constants
 */
library MazeConstants {
    /// @notice Maximum total cells in a maze (width * height)
    uint256 internal constant MAX_MAZE_CELLS = 3000;

    /// @notice Maximum packed bytes for cell data (2 cells per byte)
    uint256 internal constant MAX_PACKED_BYTES = 1500;

    /// @notice Maximum number of moves in a solution
    uint256 internal constant MAX_MOVES = 1000;

    /**
     * @notice Number of public inputs for ZK proof verification
     * @dev [maze_hash, move_count] under hash-as-public-input architecture
     */
    uint256 internal constant PUBLIC_INPUTS_LENGTH = 2;

    /// @notice Header bytes for the canonical layout (8 BE u16 fields)
    uint256 internal constant LAYOUT_HEADER_BYTES = 16;

    /// @notice Total bytes of the canonical layout (header + zero-padded cells)
    uint256 internal constant LAYOUT_TOTAL_BYTES = 1516;
}
