// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Strings } from "@openzeppelin/contracts/utils/Strings.sol";

/**
 * @title MazePalette
 * @notice Auto-generated canonical palette for MazeKing.
 * @dev Source: palette/paletteRecipe.json
 *      DO NOT EDIT THIS FILE MANUALLY.
 *      Regenerate with: just generate-palette
 *
 *      The TS counterpart (frontend/src/lib/paletteRecipe.generated.ts) is
 *      generated from the same source. Hand-edits to either file silently
 *      drift the live canvas off the on-chain NFT — see ma-fy3 /
 *      2026-05-05 retrospective §11.A.
 */
library MazePalette {
    using Strings for uint256;

    struct Palette {
        string wall;
        string mazeBg;
        string textBg;
        string zkBg;
        string crownBg;
    }

    /// @dev Build an HSL palette deterministically from `seed`. We emit HSL
    ///      strings rather than RGB so the SVG client does the conversion —
    ///      that's free for us and keeps the bytecode small.
    function palette(uint256 seed) internal pure returns (Palette memory p) {
        uint256 baseHue = seed % 360;

        // Dark, moderately saturated. Stays legible against any bg.
        p.wall = _hsl(baseHue, 25, 22);

        // Soft, lightly saturated complement to walls.
        p.mazeBg = _hsl((baseHue + 30) % 360, 22, 80);

        // Vibrant complementary hue — letters jump out against bg.
        p.textBg = _hsl((baseHue + 200) % 360, 80, 60);

        // Triadic offset from textBg (200 + 120). ZK-letter highlight.
        p.zkBg = _hsl((baseHue + 320) % 360, 80, 55);

        // Always gold, regardless of seed — crown tier reads as gold everywhere.
        p.crownBg = _hsl(48, 85, 55);
    }

    function _hsl(uint256 h, uint256 s, uint256 l) internal pure returns (string memory) {
        return string(
            abi.encodePacked("hsl(", h.toString(), ",", s.toString(), "%,", l.toString(), "%)")
        );
    }
}
