// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title MazeConstants
 * @notice Auto-generated maze constants from maze-config.json
 * @dev Generated at: 2026-01-30T17:40:07.195Z
 *      DO NOT EDIT THIS FILE MANUALLY
 *      Regenerate with: just generate-constants
 */
library MazeConstants {
    /// @notice Maximum total cells in a maze (width * height)
    uint256 internal constant MAX_MAZE_CELLS = 3000;

    /// @notice Maximum packed bytes for cell data (2 cells per byte)
    uint256 internal constant MAX_PACKED_BYTES = 1500;

    /// @notice Maximum number of moves in a solution
    uint256 internal constant MAX_MOVES = 1000;

    /**
     * @notice Number of public inputs for ZK proof verification
     * @dev = 8 scalar params + MAX_PACKED_BYTES + 1 move_count
     */
    uint256 internal constant PUBLIC_INPUTS_LENGTH = 1509;

    /**
     * @notice Number of elements used for maze identity hash (tokenId)
     * @dev = PUBLIC_INPUTS_LENGTH - 1 (excludes move_count)
     */
    uint256 internal constant MAZE_DATA_LENGTH = 1508;
}
